### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

### ISSUE THREAD

**Issue by abhilash29** [revdotcom/revai-python-sdk#37]
![untitled____PycharmProjects_untitled_](https://user-images.githubusercontent.com/1309199/66019096-76a79b80-e4ff-11e9-86b6-3e8ba780e792.png)

I'm trying to run the microphone sample from the examples directory and this is what I'm facing.

**Comment by kbridbur** [comment]
It looks as though the machine or process you are sending this from lacks an SSL Certificate. You should install a valid SSL certificate on whatever is running the example.

**Comment by abhilash29** [comment]
> It looks as though the machine or process you are sending this from lacks an SSL Certificate. You should install a valid SSL certificate on whatever is running the example.

I'm currently on macOS 10.15 and I have the certificates installed. In spite of that, I'm still getting the same error.
![Keychain_Access_and_ssl_SSLCertVerificationError___SSL__CERTIFICATE_VERIFY_FAILED__certificate_verify_failed__unable_to_get_local_issuer_certificate___ssl_c_1076__·_Issue__37_·_revdotcom_revai-python-sdk](https://user-images.githubusercontent.com/1309199/66026552-b3cb5800-e516-11e9-9b83-c66ad2bc2e1f.png)

**Comment by abhilash29** [comment]
I finally managed to fix the issue. Reference - [https://www.dev2qa.com/how-to-fix-python-error-certificate-verify-failed-unable-to-get-local-issuer-certificate-in-mac-os/](url)

**Comment by kbridbur** [comment]
Glad to see you've solved it. Since this issue was not related to the SDK or our API I will be closing this issue.

Let me know if you have other questions :)
