### ISSUE TITLE
Microphone example - How to?

### ISSUE THREAD

**Issue by abhilash29** [revdotcom/revai-python-sdk#38]
In your [microphone](https://github.com/revdotcom/revai-python-sdk/blob/develop/examples/microphone_streaming_example.py) example, 

```
example_mc = MediaConfig('audio/x-raw', 'interleaved', 44100, 'S16LE', 1)
streamclient = RevAiStreamingClient(access_token, example_mc)
```

How do I pass my speech? Can you give a sample example where there's a GUI to do it?

**Comment by kbridbur** [comment]
You should insert your access token where specified and run the example from terminal. It will take input from your microphone and transcribe that.

May I ask what you're trying to use our API for? I may be able to give you a better suggestion for how you should be interfacing with us

**Comment by abhilash29** [comment]
> You should insert your access token where specified and run the example from terminal. It will take input from your microphone and transcribe that.
> 
> May I ask what you're trying to use our API for? I may be able to give you a better suggestion for how you should be interfacing with us

I tried speaking however, the terminal kept showing this.

![rev-stream____PycharmProjects_rev-stream__-_____app_py](https://user-images.githubusercontent.com/1309199/66072378-8ca27400-e572-11e9-8adc-a942f5eb4822.png)

**Comment by kbridbur** [comment]
It looks like pyAudio may be having trouble getting any output from your microphone. To test this can you please try writing the `MicrophoneStream` to a `.wav` file and playing it? 

You should be able to do this using the following python script
```
import pyaudio
import wave
 
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100
CHUNK = 1024
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = "file.wav"
 
audio = pyaudio.PyAudio()
 
# start Recording
stream = audio.open(format=FORMAT, channels=CHANNELS,
                rate=RATE, input=True,
                frames_per_buffer=CHUNK)
print "recording..."
frames = []
 
for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
    data = stream.read(CHUNK)
    frames.append(data)
print "finished recording"
 
 
# stop Recording
stream.stop_stream()
stream.close()
audio.terminate()
 
waveFile = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
waveFile.setnchannels(CHANNELS)
waveFile.setsampwidth(audio.get_sample_size(FORMAT))
waveFile.setframerate(RATE)
waveFile.writeframes(b''.join(frames))
waveFile.close()
```

**Comment by abhilash29** [comment]
> It looks like pyAudio may be having trouble getting any output from your microphone. To test this can you please try writing the `MicrophoneStream` to a `.wav` file and playing it?
> 
> You should be able to do this using the following python script
> 
> ```
> import pyaudio
> import wave
>  
> FORMAT = pyaudio.paInt16
> CHANNELS = 1
> RATE = 44100
> CHUNK = 1024
> RECORD_SECONDS = 5
> WAVE_OUTPUT_FILENAME = "file.wav"
>  
> audio = pyaudio.PyAudio()
>  
> # start Recording
> stream = audio.open(format=FORMAT, channels=CHANNELS,
>                 rate=RATE, input=True,
>                 frames_per_buffer=CHUNK)
> print "recording..."
> frames = []
>  
> for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
>     data = stream.read(CHUNK)
>     frames.append(data)
> print "finished recording"
>  
>  
> # stop Recording
> stream.stop_stream()
> stream.close()
> audio.terminate()
>  
> waveFile = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
> waveFile.setnchannels(CHANNELS)
> waveFile.setsampwidth(audio.get_sample_size(FORMAT))
> waveFile.setframerate(RATE)
> waveFile.writeframes(b''.join(frames))
> waveFile.close()
> ```

The file is generated but audio is blank.

**Comment by kbridbur** [comment]
It looks like pyAudio isn't able to get any output from your microphone. PyAudio is a third party package which I don't know the internals of so I cant tell you exactly what's wrong. I would recommend trying to figure out why PyAudio is unable to get input from your machine. 

This seems like a good starting point https://stackoverflow.com/questions/43947294/i-have-trouble-with-pyaudio-does-not-detect-input-device

**Comment by kbridbur** [comment]
I'm going to close this issue because it is not relevant to the SDK or our API, feel free to contact me at kyle@rev.com if you're unable to get PyAudio to work for you.

**Comment by abhilash29** [comment]
> I'm going to close this issue because it is not relevant to the SDK or our API, feel free to contact me at [kyle@rev.com](mailto:kyle@rev.com) if you're unable to get PyAudio to work for you.

Thanks for pointing out in the right direction. It was indeed a Pyaudio issue. I tried it on another machine (Ubuntu) and it worked.

**Comment by kbridbur** [comment]
Glad to hear it worked! Best of luck
