### ISSUE TITLE
remove src/__init__.py and move rev_api to top level

### ISSUE THREAD

**Issue by devendralaulkar** [revdotcom/revai-python-sdk#51]
src/__init__.py gets copied over to site_packages directory. This causes issues with pylint and seems to be a bad idea to place this file in site_packages.
Stumbled upon the file while trying to fix pylint and this article pointed me in the right direction.
https://jamesmallen.net/2018/01/29/pylint_django-error-nosuchchecker/

**Comment by KostasRev** [comment]
Hi Devendra,

Can you please elaborate on what the problem you are trying to solve is?

Also can you please elaborate on how you encountered the problem? Was it while trying to integrate the SDK it into a project you are working on?

If you can, please include the relevant error message in addition to the above.

Thanks

**Comment by amikofalvy** [comment]
Closing stale issues.
