### ISSUE TITLE
Broken Settings Page link to Access Token

### ISSUE THREAD

**Issue by nbmurphy** [revdotcom/revai-python-sdk#64]
The **Settings Page** link in this statement of your README is broken:
_All you need to get started is your Access Token, which can be generated on your Settings Page. Create a client with the given Access Token:_

Will you please let me know how to get an access token.

**Comment by amikofalvy** [comment]
Thanks for the note. I've updated the README to use the correct link. Link: https://www.rev.ai/access_token

Follow the above link to generate your access token. Then complete the instructions on the [getting started page](https://www.rev.ai/getting_started)

This change was implemented in this commit:
https://github.com/revdotcom/revai-python-sdk/commit/1d73a5436679c1d176603697da79dbb49ac96759
