### ISSUE TITLE
2.11.0 hasn't been published to PyPI

### ISSUE THREAD

**Issue by s16h** [revdotcom/revai-python-sdk#65]

**Comment by amikofalvy** [comment]
The release is scheduled to go out within a week.

**Comment by s16h** [comment]
Thanks — the versioning pinning of `requests` in 2.10.0 is causing a lot of pain.

**Comment by amikofalvy** [comment]
Rev.ai Python SDK 2.11.0 is released. https://pypi.org/project/rev-ai/2.11.0/

Thanks for reaching out.
