### ISSUE TITLE
machine_v2 option for local files?

### ISSUE THREAD

**Issue by MarkAPitt** [revdotcom/revai-python-sdk#74]
Using the Python API, I get the following error when running an async job specifying 'transcriber."

 File "<ipython-input-9-4df442e36d0a>", line 8, in <module>
    transcriber = 'machine_v2')

TypeError: submit_job_local_file() got an unexpected keyword argument 'transcriber'

`    job = client.submit_job_local_file(
            filename = outputaudiofilename,
            skip_diarization = True,
            skip_punctuation = True,
            remove_disfluencies = True,
            speaker_channels_count = 1,
            language ="en",
            transcriber = "machine_v2")
 `

**Comment by kbridbur** [comment]
Hi Mark, this feature was just added to the SDK repository recently and has not yet been released. We're planning to release a new version of the SDK which allows this parameter in the next few days and then this request will work. I will update and close this issue when the new version is released.

**Comment by kbridbur** [comment]
Hello again, version 2.14.0 has just been released and contains the transcriber parameter. Please update your version of the SDK and you should be able to use this
