### ISSUE TITLE
missed words

### ISSUE THREAD

**Issue by MarkAPitt** [revdotcom/revai-python-sdk#75]
Are there plans to add a switch to return IDK or "null" on low-confidence matches? When the engine fails to return a word, but knows speech is present, it would be good to record this.

**Comment by kbridbur** [comment]
We actually have this feature already, it comes in the form of unknown tokens, if we detect that speech is present but are unable to discern its meaning there will be an element in the monologue with a type of `unknown` and a value of `<inaudible>`, documentation for the transcript format can be found [here](https://www.rev.ai/docs#operation/GetTranscriptById).
