### ISSUE TITLE
Backend also updated?

### ISSUE THREAD

**Issue by kalling** [revdotcom/revai-python-sdk#8]
Since you guys did the API cleanup I have not been able to submit a job with my old code using 0.0.3

It fails during json decoding.  (It expecting something, but there was nothing)

I also tried cloning your current version.  (Even though that's not what you have on pypi)
and after fixing a formatting issue in apiclient.py I did a submission, but it fails in the json decoder just like it does with the 0.0.3 version.

BTW, I think that submit_job_local_file() and submit_job_url() would be better if you kept options as optional with sensible defaults instead of forcing the construction of an options class.

**Comment by kbridbur** [comment]
Hi Richard, sorry to hear about your problem. I'm happy to help you debug the problem, it would be very helpful if you could send me the error and a snippet of the code that's causing it so I can reproduce. If you could send me those at kyle@rev.com I'll take a look.

Also, I completely agree with your suggestion for the options parameter, I'll add that change in my next PR

**Comment by kbridbur** [comment]
Posting here to say that this issue should be solved. The API previously had an issue with very long files, this should be fixed now
