### ISSUE TITLE
How to specify transcription with v1?

### ISSUE THREAD

**Issue by connormeaton** [revdotcom/revai-python-sdk#82]
In certain cases, I find the v1 transcriptions to be preferable to the v2 transcriptions. How do I specify which version to use in python? Currently, I submit a job with this:
```
    token = 'TOKEN'
    client = apiclient.RevAiAPIClient(token)
    # initiate request
    job = client.submit_job_local_file(audio_path)
    x = 1
    # Create waiting mechanism for rev.ai to process files.
    while x == 1:
        try:
            # get transcript as json
            transcript_json = client.get_transcript_json(job.id)
            # save output
            rev_json_saved_path = f'rev_json/{audio_id}.json' 
            with open(path, 'w') as f:
                json.dump(transcript_json, f)
            x -= 1
        except:
            time.sleep(3)
```
I see in the docs below that I can set 'transcriber' to 'machine', 'machine_v2', or 'human'. 
https://docs.rev.ai/api/asynchronous/transcribers/

First, where do I enter the 'transcriber' parameter in python code?

Second, if v2 is now default, what is the parameter for v1?

Thank you.

**Comment by amikofalvy** [comment]
We are highly encouraging all of our customers to switch over to the v2 ASR model as it has [significant improvements in Turn Around Time and Word Error Rate as compared to the V1 model.](https://www.rev.ai/blog/rev-improves-accuracy-by-over-25-with-launch-of-new-v2-asr-model/)

As such, there is no API option on the end user side that allows you to continue use of ASR v1. Specifying "machine" as the transcriber will default you to use ASR v2 after the cutover date April 8th, 2022.

However you can request our support to configure an internal setting which will lock your transcription to the ASR v1 model until September 8th, 2022 (See the section on [deferred migration](https://docs.rev.ai/api/asynchronous/transcribers/#deferred-migration)).

I would highly encourage you to explain why you would like to continue use of the ASR v1 when you fill out the [Deferred Migration request form](https://docs.google.com/forms/d/e/1FAIpQLSdscNO-3bscblI8fScW7pRsjUFRn7XI0UNuZQVCv1pLfmeBAQ/viewform)
